name: churn_prediction
channels:
  - conda-forge
dependencies:
  - python=3.13.9
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - jupyterlab
  - pip
  - openpyxl
  - math
  - datetime
  - statsmodels
  - pip:
      - seaborn
      - xgboost